### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by skysthelimitt** [Barney-CO/Epic-School-Center#2]
hey, i made selenite!
if you're gonna use my games and scripts, could you please at least give some sort of credit?
it takes a while to make selenite, and so id prefer if i at least got credit
ty :)

**Comment by BarneyAtAldi2** [comment]
> hey, i made selenite!
> 
> if you're gonna use my games and scripts, could you please at least give some sort of credit?
> 
> it takes a while to make selenite, and so id prefer if i at least got credit
> 
> ty :)

Hey I'm sorry I didn't credit you I'll try to asap
